### ISSUE TITLE
Change backslashes to forward slashes

### ISSUE THREAD

**Issue by sgoodgrove** [dariusz-wozniak/List-of-Testing-Tools-and-Frameworks-for-.NET#14]
Excellent list, one suggestion. The back-slashes ( `\` ) look a bit odd to my eyes. I recommend changing them to forward slashes ( `/` ) happy to submit a PR if you would like.

**Comment by dariusz-wozniak** [comment]
Hi, thanks! I'm open for changing back-slashes to slashes, but I would like to know what's the reason. Is that a personal preference? Or, can it be argued by studies? Or, is that a part of one of the Manual of Style?

**Comment by sgoodgrove** [comment]
I think it’s fair to say that in common English they are literally never used, so to see them at all looks very peculiar indeed and makes the text a little bit less fluid to read.

**Comment by dariusz-wozniak** [comment]
You're right, didn't know about that and that's an interesting fact. I will make a change then.
