### ISSUE TITLE
User interface testing - updates

### ISSUE THREAD

**Issue by LaiaPR** [dariusz-wozniak/List-of-Testing-Tools-and-Frameworks-for-.NET#27]
Hi! Thank you for this work, it has helped me to know more tools ;)

I want to suggest some updates in [User interface testing](https://github.com/dariusz-wozniak/List-of-Testing-Tools-and-Frameworks-for-.NET#user-interface-testing) section:

- [White ](https://github.com/TestStack/White) is deprecated 
- Regarding **WinAppDriver**, you can use it integrated with [Appium ](https://appium.io/docs/en/drivers/windows/) or [SpecFlow ](https://docs.specflow.org/en/latest/Examples.html)
- you can add [Ranorex ](https://www.ranorex.com/)

**Comment by dariusz-wozniak** [comment]
Thank you for your suggestions and glat it helped, @LaiaPR :)

Changes done. Please let me know if you have any more suggestions 👍
