### ISSUE TITLE
Foq not available any more & a new extension I wrote

### ISSUE THREAD

**Issue by mattwhitfield** [dariusz-wozniak/List-of-Testing-Tools-and-Frameworks-for-.NET#28]
Hello

I came across this while I was writing a unit testing extension - https://marketplace.visualstudio.com/items?itemName=MattWhitfield.Unitverse. It would be great if you could add it to the list.

But the main thing was I think Foq is no more - I certainly couldn't find any evidence of it still existing...

Thanks for the list, super useful. 👍

**Comment by dariusz-wozniak** [comment]
Great, thank you for suggestions!

I added Unitverse (it looks pretty nice though!) and updated Foq information.
