### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by antoops** [dariusz-wozniak/List-of-Testing-Tools-and-Frameworks-for-.NET#3]
Under BDD, the link for Machine.Specifications (also known as MSpec) is broken

https://github.com/machine/machine.specifications

**Comment by dariusz-wozniak** [comment]
Hi @antoops,
The link for machine.specifications ([https://github.com/machine/machine.specifications](https://github.com/machine/machine.specifications)) works fine.
Did you mean that link?
